//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class K_U_Jobs
{
    public string ID { get; set; }
    public Nullable<int> IsDel { get; set; }
    public Nullable<int> IsEnable { get; set; }
    public Nullable<int> IsArchiving { get; set; }
    public Nullable<long> Orders { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public Nullable<System.DateTime> DelTime { get; set; }
    public int SiteID { get; set; }
    public string NodeCode { get; set; }
    public Nullable<int> FlowState { get; set; }
    public string ReferenceID { get; set; }
    public string AddMan { get; set; }
    public string Title { get; set; }
    public string WorkAddr { get; set; }
    public string Num { get; set; }
    public string Salary { get; set; }
    public Nullable<System.DateTime> PubDate { get; set; }
    public string Requirement { get; set; }
    public string Content { get; set; }
}

public partial class K_U_News
{
    public string ID { get; set; }
    public Nullable<int> IsDel { get; set; }
    public Nullable<int> IsEnable { get; set; }
    public Nullable<int> IsArchiving { get; set; }
    public Nullable<long> Orders { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public Nullable<System.DateTime> DelTime { get; set; }
    public int SiteID { get; set; }
    public string NodeCode { get; set; }
    public Nullable<int> FlowState { get; set; }
    public string ReferenceID { get; set; }
    public string AddMan { get; set; }
    public string MetaDescript { get; set; }
    public string MetaKeyword { get; set; }
    public string Title { get; set; }
    public string TitleImg { get; set; }
    public Nullable<System.DateTime> PubDate { get; set; }
    public string Intro { get; set; }
    public string Content { get; set; }
    public string Attach { get; set; }
    public string PageTitle { get; set; }
    public int IsHtml { get; set; }
}

public partial class K_U_product
{
    public string ID { get; set; }
    public Nullable<int> IsDel { get; set; }
    public Nullable<int> IsEnable { get; set; }
    public Nullable<int> IsArchiving { get; set; }
    public Nullable<long> Orders { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public Nullable<System.DateTime> DelTime { get; set; }
    public int SiteID { get; set; }
    public string NodeCode { get; set; }
    public Nullable<int> FlowState { get; set; }
    public string ReferenceID { get; set; }
    public string AddMan { get; set; }
    public string MetaDescript { get; set; }
    public string MetaKeyword { get; set; }
    public string Title { get; set; }
    public Nullable<System.DateTime> PubDate { get; set; }
    public string Intro { get; set; }
    public string BigImg { get; set; }
    public string Content { get; set; }
    public string SmallImg { get; set; }
    public string Attach { get; set; }
    public string tuij { get; set; }
    public string productuse { get; set; }
    public string PageTitle { get; set; }
    public int IsHtml { get; set; }
    public string xc { get; set; }
    public string dtcs { get; set; }
    public string jjfa { get; set; }
    public string cpal { get; set; }
}

public partial class K_U_Show
{
    public string ID { get; set; }
    public Nullable<int> IsDel { get; set; }
    public Nullable<int> IsEnable { get; set; }
    public Nullable<int> IsArchiving { get; set; }
    public Nullable<long> Orders { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public Nullable<System.DateTime> DelTime { get; set; }
    public int SiteID { get; set; }
    public string NodeCode { get; set; }
    public Nullable<int> FlowState { get; set; }
    public string ReferenceID { get; set; }
    public string AddMan { get; set; }
    public string Title { get; set; }
    public string ShowDate { get; set; }
    public string Addr { get; set; }
    public string Team { get; set; }
}
