//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class Entities : DbContext
{
    public Entities()
        : base("name=Entities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<K_U_Jobs> K_U_Jobs { get; set; }
    public virtual DbSet<K_U_News> K_U_News { get; set; }
    public virtual DbSet<K_U_product> K_U_product { get; set; }
    public virtual DbSet<K_U_Show> K_U_Show { get; set; }
}
