//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class EntitiesConfigName : DbContext
{
    public EntitiesConfigName()
        : base("name=EntitiesConfigName")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<K_Category> K_Category { get; set; }
    public virtual DbSet<K_F_FeedBack> K_F_FeedBack { get; set; }
}
