//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class K_Category
{
    public int ID { get; set; }
    public string Name { get; set; }
    public int ParentID { get; set; }
    public string ParentName { get; set; }
    public string ArrayParentID { get; set; }
    public Nullable<int> Child { get; set; }
    public string ArrayChildID { get; set; }
    public Nullable<int> Orders { get; set; }
    public string AddMan { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public Nullable<int> IsValid { get; set; }
    public Nullable<int> IsIndex { get; set; }
    public string NodeCode { get; set; }
    public Nullable<int> SiteID { get; set; }
    public string Description { get; set; }
    public Nullable<int> IsDel { get; set; }
    public Nullable<System.DateTime> delTime { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
    public Nullable<int> Depth { get; set; }
    public string ColumnID { get; set; }
    public string PageTitle { get; set; }
    public string PageKeywords { get; set; }
    public string PageDescription { get; set; }
    public string URLRewriter { get; set; }
    public string CateType { get; set; }
    public string Img { get; set; }
}

public partial class K_F_FeedBack
{
    public string ID { get; set; }
    public Nullable<int> IsDel { get; set; }
    public Nullable<int> IsEnable { get; set; }
    public Nullable<int> IsArchiving { get; set; }
    public Nullable<long> Orders { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public Nullable<System.DateTime> DelTime { get; set; }
    public int SiteID { get; set; }
    public string NodeCode { get; set; }
    public Nullable<int> FlowState { get; set; }
    public string ReferenceID { get; set; }
    public string AddMan { get; set; }
    public string IP { get; set; }
    public string Title { get; set; }
    public string Name { get; set; }
    public string EMail { get; set; }
    public string LinkPhone { get; set; }
    public string LinkAddress { get; set; }
    public string Content { get; set; }
    public string DealResult { get; set; }
}
