//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class K_Act
{
    public string id { get; set; }
}

public partial class K_Category
{
    public int ID { get; set; }
    public string Name { get; set; }
    public int ParentID { get; set; }
    public string ParentName { get; set; }
    public string ArrayParentID { get; set; }
    public Nullable<int> Child { get; set; }
    public string ArrayChildID { get; set; }
    public Nullable<int> Orders { get; set; }
    public string AddMan { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public Nullable<int> IsValid { get; set; }
    public Nullable<int> IsIndex { get; set; }
    public string NodeCode { get; set; }
    public Nullable<int> SiteID { get; set; }
    public string Description { get; set; }
    public Nullable<int> IsDel { get; set; }
    public Nullable<System.DateTime> delTime { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
    public Nullable<int> Depth { get; set; }
    public string ColumnID { get; set; }
    public string PageTitle { get; set; }
    public string PageKeywords { get; set; }
    public string PageDescription { get; set; }
    public string URLRewriter { get; set; }
    public string CateType { get; set; }
    public string Img { get; set; }
}

public partial class K_F_FeedBack
{
    public string ID { get; set; }
    public Nullable<int> IsDel { get; set; }
    public Nullable<int> IsEnable { get; set; }
    public Nullable<int> IsArchiving { get; set; }
    public Nullable<long> Orders { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public Nullable<System.DateTime> DelTime { get; set; }
    public int SiteID { get; set; }
    public string NodeCode { get; set; }
    public Nullable<int> FlowState { get; set; }
    public string ReferenceID { get; set; }
    public string AddMan { get; set; }
    public string IP { get; set; }
    public string Title { get; set; }
    public string Name { get; set; }
    public string EMail { get; set; }
    public string LinkPhone { get; set; }
    public string LinkAddress { get; set; }
    public string Content { get; set; }
    public string DealResult { get; set; }
}

public partial class K_FlowStep
{
    public string ID { get; set; }
    public Nullable<int> Orders { get; set; }
    public Nullable<bool> IsDel { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public string AddMan { get; set; }
    public string Name { get; set; }
    public string Desc { get; set; }
    public string SuccessName { get; set; }
    public Nullable<int> SuccessState { get; set; }
    public string FailName { get; set; }
    public Nullable<int> FailState { get; set; }
    public string GroupID { get; set; }
    public string ReviewFlowStateGroup { get; set; }
    public string ReviewFlowId { get; set; }
    public Nullable<bool> IsEnable { get; set; }
    public string NodeCode { get; set; }
    public Nullable<System.DateTime> delTime { get; set; }
}

public partial class K_HRApplyJob
{
    public int ID { get; set; }
    public int ResumeID { get; set; }
    public string MemberName { get; set; }
    public int JobID { get; set; }
    public System.DateTime AddDate { get; set; }
    public int Status { get; set; }
}

public partial class K_HRJob
{
    public int ID { get; set; }
    public string Title { get; set; }
    public string JobType { get; set; }
    public string WorkUnit { get; set; }
    public string WorkPlace { get; set; }
    public string Salary { get; set; }
    public string Degree { get; set; }
    public Nullable<short> Age { get; set; }
    public string Experience { get; set; }
    public string Number { get; set; }
    public string EMail { get; set; }
    public Nullable<System.DateTime> PublishDate { get; set; }
    public Nullable<System.DateTime> EndDate { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public string WorkDuty { get; set; }
    public string Qualifications { get; set; }
    public string Welfare { get; set; }
    public Nullable<short> FlowState { get; set; }
    public string AddMan { get; set; }
    public string NodeCode { get; set; }
    public Nullable<short> SiteID { get; set; }
    public Nullable<int> Orders { get; set; }
    public short IsDel { get; set; }
    public Nullable<System.DateTime> DelTime { get; set; }
    public string PageTitle { get; set; }
    public string MetaKeyword { get; set; }
    public string MetaDescript { get; set; }
    public Nullable<bool> IsHtml { get; set; }
    public Nullable<System.DateTime> LastViewResume { get; set; }
}

public partial class K_HRJobCate
{
    public string ID { get; set; }
    public string ParentID { get; set; }
    public string Title { get; set; }
    public string Intro { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public Nullable<short> FlowState { get; set; }
    public Nullable<short> IsDel { get; set; }
    public Nullable<System.DateTime> DelTime { get; set; }
    public Nullable<short> SiteID { get; set; }
    public string NodeCode { get; set; }
    public string CateType { get; set; }
    public Nullable<short> Orders { get; set; }
}

public partial class K_HRResume
{
    public int ID { get; set; }
    public string MemberName { get; set; }
    public string UserName { get; set; }
    public string Nation { get; set; }
    public string Gender { get; set; }
    public Nullable<System.DateTime> Birthday { get; set; }
    public string CardID { get; set; }
    public Nullable<short> Weight { get; set; }
    public string Marriage { get; set; }
    public Nullable<int> Height { get; set; }
    public string Photo { get; set; }
    public string City { get; set; }
    public string NativePlace { get; set; }
    public Nullable<bool> IsRoom { get; set; }
    public int WorkYear { get; set; }
    public string Universities { get; set; }
    public string Specialty { get; set; }
    public string Degree { get; set; }
    public string EnglishLevel { get; set; }
    public string ComputerLevel { get; set; }
    public string Industry { get; set; }
    public string Post { get; set; }
    public string CurrentSalary { get; set; }
    public string RequiresSalary { get; set; }
    public string Mobile { get; set; }
    public string Tel { get; set; }
    public string EMail { get; set; }
    public string QQ { get; set; }
    public string Address { get; set; }
    public string Hobbies { get; set; }
    public string Speciality { get; set; }
    public string ZipCode { get; set; }
    public string InformationWay { get; set; }
    public string PostExpect { get; set; }
    public string CompanyExpect { get; set; }
    public Nullable<System.DateTime> ReportDate { get; set; }
    public string WorkExperience { get; set; }
    public string WorkDescription { get; set; }
    public string SkillsExpertise { get; set; }
    public string EducationalBackground { get; set; }
    public string Train { get; set; }
    public Nullable<int> SiteID { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public Nullable<int> IsDel { get; set; }
    public Nullable<System.DateTime> DelTime { get; set; }
    public string NodeCode { get; set; }
    public Nullable<bool> IsRead { get; set; }
    public Nullable<System.DateTime> UpdateDate { get; set; }
    public string Memo { get; set; }
}

public partial class K_Member
{
    public System.Guid MemberID { get; set; }
    public string UserName { get; set; }
    public string Password { get; set; }
    public string GroupID { get; set; }
    public string ModleID { get; set; }
    public string Email { get; set; }
    public Nullable<double> Funds { get; set; }
    public Nullable<double> FundFreeze { get; set; }
    public int Point { get; set; }
    public int Integral { get; set; }
    public Nullable<byte> StateID { get; set; }
    public Nullable<byte> IsCheck { get; set; }
    public bool IsEmailValid { get; set; }
    public Nullable<bool> IsDel { get; set; }
    public string RegitIP { get; set; }
    public System.DateTime RegitDate { get; set; }
    public string PreLoginIP { get; set; }
    public Nullable<System.DateTime> PreLoginDate { get; set; }
    public string LastLoginIP { get; set; }
    public Nullable<System.DateTime> LastLoginDate { get; set; }
    public Nullable<System.DateTime> LastPub { get; set; }
    public int LoginTimes { get; set; }
    public string NodeCode { get; set; }
    public Nullable<int> SiteID { get; set; }
    public string HeadImg { get; set; }
    public string ThemeID { get; set; }
    public string UserGroup { get; set; }
    public string PubTipLevel { get; set; }
    public int ReadRight { get; set; }
    public int Golds { get; set; }
    public int Prestige { get; set; }
    public int SaveGolds { get; set; }
    public int Tips { get; set; }
    public int VeryTips { get; set; }
    public int TotalOnlineHour { get; set; }
    public int MonthHour { get; set; }
    public string Moderator { get; set; }
    public int BestAnswerCount { get; set; }
    public string Gender { get; set; }
    public string Token { get; set; }
    public string PwdVe { get; set; }
    public string RealName { get; set; }
    public Nullable<System.DateTime> Birthday { get; set; }
    public string Mobile { get; set; }
    public Nullable<byte> Marriage { get; set; }
    public string Intro { get; set; }
}

public partial class K_MemberGroup
{
    public string ID { get; set; }
    public string GroupName { get; set; }
    public string ServerIntro { get; set; }
    public Nullable<byte> IsVisit { get; set; }
    public Nullable<byte> IsSearch { get; set; }
    public Nullable<byte> IsPub { get; set; }
    public Nullable<byte> IsSelfUpgrade { get; set; }
    public Nullable<double> YearPrices { get; set; }
    public Nullable<double> MonthPrices { get; set; }
    public Nullable<double> DayPrices { get; set; }
    public Nullable<byte> IsDisable { get; set; }
    public Nullable<int> Orders { get; set; }
    public Nullable<bool> IsDel { get; set; }
    public string AddMan { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public string NodeCode { get; set; }
    public Nullable<int> SiteID { get; set; }
    public Nullable<int> Toplimit { get; set; }
    public Nullable<int> Lowerlimit { get; set; }
    public Nullable<int> Discount { get; set; }
    public Nullable<bool> IsShowPrice { get; set; }
}

public partial class K_ModelCommonField
{
    public System.Guid ID { get; set; }
    public string Name { get; set; }
    public Nullable<System.Guid> CommonFieldGroupID { get; set; }
    public string FieldAlias { get; set; }
    public string BasicField { get; set; }
    public string Message { get; set; }
    public string EditorStyle { get; set; }
    public Nullable<long> TextBoxMaxLength { get; set; }
    public Nullable<long> TextBoxWidth { get; set; }
    public Nullable<long> TextBoxHieght { get; set; }
    public string TextBoxValidation { get; set; }
    public string ValidationType { get; set; }
    public string ValidationMessage { get; set; }
    public Nullable<bool> IsLink { get; set; }
    public Nullable<bool> IsFilter { get; set; }
    public Nullable<bool> IsShield { get; set; }
    public string EditorType { get; set; }
    public string OptionsValue { get; set; }
    public Nullable<int> OptionCount { get; set; }
    public Nullable<bool> IsFill { get; set; }
    public string MinValue { get; set; }
    public string MaxValue { get; set; }
    public string DefaultValue { get; set; }
    public string DateDefaultOption { get; set; }
    public string DateFormatOption { get; set; }
    public Nullable<bool> IsUpload { get; set; }
    public Nullable<int> MaxSize { get; set; }
    public string ImageType { get; set; }
    public string ImageNameRules { get; set; }
    public Nullable<bool> ImageIsWatermark { get; set; }
    public Nullable<bool> IsUploadThumbnail { get; set; }
    public Nullable<bool> IsSaveFileSize { get; set; }
    public string SaveFileName { get; set; }
    public string UrlPrefix { get; set; }
    public Nullable<bool> IsRequired { get; set; }
    public Nullable<bool> IsEnable { get; set; }
    public Nullable<long> Orders { get; set; }
    public Nullable<bool> IsSearch { get; set; }
    public Nullable<long> SearchWidth { get; set; }
    public Nullable<long> SearchOrders { get; set; }
    public string ListWidth { get; set; }
    public string ListAlignment { get; set; }
    public Nullable<long> ListOrders { get; set; }
    public Nullable<bool> ListIsLink { get; set; }
    public string ListLinkUrl { get; set; }
    public Nullable<bool> ListIsOrder { get; set; }
    public string ListOrderOption { get; set; }
    public Nullable<bool> ListIsDefaultOrder { get; set; }
    public string ListDefaultOrderOption { get; set; }
    public string UserGroupId { get; set; }
    public string RoleGroupId { get; set; }
    public Nullable<System.DateTime> AddTime { get; set; }
    public string UserNo { get; set; }
    public string DropDownDataType { get; set; }
    public string DropDownTable { get; set; }
    public string DropDownTextColumn { get; set; }
    public string DropDownValueColumn { get; set; }
    public string DropDownSql { get; set; }
    public Nullable<bool> IsListEnable { get; set; }
    public Nullable<int> NumberCount { get; set; }
    public Nullable<bool> IsDel { get; set; }
    public Nullable<bool> IsInputValue { get; set; }
    public Nullable<int> SearchUIType { get; set; }
    public string DropDownSqlWhere { get; set; }
    public Nullable<int> DataColumnLength { get; set; }
    public Nullable<int> ModelFieldType { get; set; }
    public Nullable<bool> IsListVisible { get; set; }
    public Nullable<bool> IsMultiFile { get; set; }
    public string Controls { get; set; }
    public Nullable<int> ThumbDisplayType { get; set; }
    public Nullable<int> ThumbWidth { get; set; }
    public Nullable<int> ThumbHeight { get; set; }
    public Nullable<bool> IsDefault { get; set; }
    public Nullable<System.DateTime> DelTime { get; set; }
    public string NodeCode { get; set; }
}

public partial class K_ModelCommonFieldGroup
{
    public System.Guid ID { get; set; }
    public string Name { get; set; }
    public long Orders { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public string AddMan { get; set; }
    public Nullable<bool> IsDel { get; set; }
}

public partial class K_ModelField
{
    public string ID { get; set; }
    public string ModelId { get; set; }
    public string Name { get; set; }
    public string ModelFieldGroupId { get; set; }
    public string FieldAlias { get; set; }
    public string Message { get; set; }
    public string BasicField { get; set; }
    public string EditorStyle { get; set; }
    public Nullable<long> TextBoxMaxLength { get; set; }
    public Nullable<long> TextBoxWidth { get; set; }
    public Nullable<long> TextBoxHieght { get; set; }
    public string TextBoxValidation { get; set; }
    public string ValidationType { get; set; }
    public string ValidationMessage { get; set; }
    public Nullable<bool> IsLink { get; set; }
    public Nullable<bool> IsFilter { get; set; }
    public Nullable<bool> IsShield { get; set; }
    public string EditorType { get; set; }
    public string OptionsValue { get; set; }
    public Nullable<int> OptionCount { get; set; }
    public Nullable<bool> IsFill { get; set; }
    public string MinValue { get; set; }
    public string MaxValue { get; set; }
    public string DefaultValue { get; set; }
    public string DateDefaultOption { get; set; }
    public string DateFormatOption { get; set; }
    public Nullable<bool> IsUpload { get; set; }
    public Nullable<int> MaxSize { get; set; }
    public string ImageType { get; set; }
    public string ImageNameRules { get; set; }
    public Nullable<bool> ImageIsWatermark { get; set; }
    public Nullable<bool> IsUploadThumbnail { get; set; }
    public Nullable<bool> IsSaveFileSize { get; set; }
    public string SaveFileName { get; set; }
    public string UrlPrefix { get; set; }
    public Nullable<bool> IsRequired { get; set; }
    public Nullable<bool> IsEnable { get; set; }
    public Nullable<long> Orders { get; set; }
    public Nullable<bool> IsSearch { get; set; }
    public Nullable<long> SearchWidth { get; set; }
    public Nullable<long> SearchOrders { get; set; }
    public string ListWidth { get; set; }
    public string ListAlignment { get; set; }
    public Nullable<long> ListOrders { get; set; }
    public Nullable<bool> ListIsLink { get; set; }
    public string ListLinkUrl { get; set; }
    public Nullable<bool> ListIsOrder { get; set; }
    public string ListOrderOption { get; set; }
    public Nullable<bool> ListIsDefaultOrder { get; set; }
    public string ListDefaultOrderOption { get; set; }
    public Nullable<bool> IsRss { get; set; }
    public string UserGroupId { get; set; }
    public string RoleGroupId { get; set; }
    public Nullable<System.DateTime> AddTime { get; set; }
    public string UserNo { get; set; }
    public string DropDownDataType { get; set; }
    public string DropDownTable { get; set; }
    public string DropDownTextColumn { get; set; }
    public string DropDownValueColumn { get; set; }
    public string DropDownSql { get; set; }
    public Nullable<bool> IsListEnable { get; set; }
    public Nullable<int> NumberCount { get; set; }
    public bool IsSystemFiierd { get; set; }
    public Nullable<bool> IsDel { get; set; }
    public Nullable<bool> IsInputValue { get; set; }
    public Nullable<int> SearchUIType { get; set; }
    public string DropDownSqlWhere { get; set; }
    public Nullable<int> DataColumnLength { get; set; }
    public Nullable<int> ModelFieldType { get; set; }
    public Nullable<bool> IsListVisible { get; set; }
    public string SystemFirerdHtml { get; set; }
    public Nullable<bool> IsMultiFile { get; set; }
    public string Controls { get; set; }
    public Nullable<int> ThumbDisplayType { get; set; }
    public Nullable<int> SysFieldType { get; set; }
    public Nullable<int> ThumbWidth { get; set; }
    public Nullable<int> ThumbHeight { get; set; }
    public Nullable<System.DateTime> DelTime { get; set; }
    public string NodeCode { get; set; }
    public Nullable<bool> IsInterface { get; set; }
    public Nullable<System.Guid> SubModelGroupID { get; set; }
    public Nullable<bool> IsAlbums { get; set; }
    public Nullable<int> RelatedType { get; set; }
    public string SubModelName { get; set; }
    public Nullable<bool> IsAlbumsUploadThumb { get; set; }
    public Nullable<bool> IsAlbumsDesc { get; set; }
    public Nullable<short> ImageBestWidth { get; set; }
    public Nullable<short> ImageBestHeight { get; set; }
}

public partial class K_ModelFieldGroup
{
    public string ID { get; set; }
    public string ModelId { get; set; }
    public string Name { get; set; }
    public long Orders { get; set; }
    public bool IsEnable { get; set; }
    public System.DateTime AddDate { get; set; }
}

public partial class K_ModelManage
{
    public string ID { get; set; }
    public string MenuNo { get; set; }
    public int SiteID { get; set; }
    public string Title { get; set; }
    public string TableName { get; set; }
    public string ModuleID { get; set; }
    public string SysField { get; set; }
    public string ListLink { get; set; }
    public string ListButton { get; set; }
    public string OperationColumn { get; set; }
    public string CustomCol { get; set; }
    public string Memo { get; set; }
    public long Orders { get; set; }
    public System.DateTime AddDate { get; set; }
    public bool IsEnable { get; set; }
    public bool IsDel { get; set; }
    public bool IsHtml { get; set; }
    public bool IsOrderEdit { get; set; }
    public bool IsListContentClip { get; set; }
    public Nullable<int> ListHeight { get; set; }
    public string DeliverAndSearchUrlParam { get; set; }
    public string FieldFromUrlParamValue { get; set; }
    public string OperationColumnWidth { get; set; }
    public string DeliverUrlParam { get; set; }
    public string RecommendArea { get; set; }
    public string ConfigMan { get; set; }
    public string NotSearchField { get; set; }
    public string BackDeliverUrlParam { get; set; }
    public string CommonField { get; set; }
    public Nullable<System.DateTime> DelTime { get; set; }
    public string nodecode { get; set; }
    public Nullable<bool> IsSub { get; set; }
    public Nullable<System.Guid> SubModelGroupID { get; set; }
}

public partial class K_RecyclingAssociated
{
    public int ID { get; set; }
    public Nullable<int> RecyclingManageID { get; set; }
    public Nullable<int> AssociatedID { get; set; }
    public string AssociatedKey { get; set; }
    public string AssociatedWhere { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public string AddMan { get; set; }
    public Nullable<bool> IsDel { get; set; }
    public Nullable<System.DateTime> delTime { get; set; }
    public string NodeCode { get; set; }
    public Nullable<bool> KeyIsWhere { get; set; }
}

public partial class K_RecyclingManage
{
    public int ID { get; set; }
    public string pKey { get; set; }
    public string DelKey { get; set; }
    public string TitleKey { get; set; }
    public string DelTimeKey { get; set; }
    public string NodeCode { get; set; }
    public Nullable<bool> IsManage { get; set; }
    public Nullable<bool> IsReductive { get; set; }
    public string ListUrl { get; set; }
    public string Desc { get; set; }
    public Nullable<bool> IsProcDel { get; set; }
    public string ProcDelText { get; set; }
    public Nullable<bool> IsProcReductive { get; set; }
    public string ProcReductiveText { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public string AddMan { get; set; }
    public string tableName { get; set; }
    public Nullable<bool> isDel { get; set; }
    public Nullable<System.DateTime> delTime { get; set; }
    public Nullable<bool> IsOnDesc { get; set; }
    public Nullable<bool> IsError { get; set; }
}

public partial class K_ReviewFlow
{
    public string ID { get; set; }
    public Nullable<int> Orders { get; set; }
    public Nullable<bool> IsDel { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public string AddMan { get; set; }
    public Nullable<bool> IsEnable { get; set; }
    public string Name { get; set; }
    public string Desc { get; set; }
    public string Type { get; set; }
    public string SiteId { get; set; }
    public string NodeID { get; set; }
    public string NodeCode { get; set; }
    public Nullable<System.DateTime> delTime { get; set; }
}

public partial class K_ReviewFlowLog
{
    public System.Guid ID { get; set; }
    public Nullable<int> Orders { get; set; }
    public Nullable<bool> IsDel { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public string AddMan { get; set; }
    public Nullable<bool> IsEnable { get; set; }
    public string Desc { get; set; }
    public string Notation { get; set; }
    public string IP { get; set; }
    public string NodeId { get; set; }
    public Nullable<int> SiteId { get; set; }
    public string NewsId { get; set; }
    public string ModeId { get; set; }
    public Nullable<bool> IsSuccess { get; set; }
}

public partial class K_ReviewFlowState
{
    public string ID { get; set; }
    public Nullable<int> Orders { get; set; }
    public Nullable<bool> IsDel { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public string AddMan { get; set; }
    public Nullable<int> StateValue { get; set; }
    public string Name { get; set; }
    public string Desc { get; set; }
    public Nullable<int> Type { get; set; }
    public string SiteId { get; set; }
    public string NodeId { get; set; }
    public string NodeCode { get; set; }
    public Nullable<System.DateTime> delTime { get; set; }
}

public partial class K_Special
{
    public string ID { get; set; }
    public string Name { get; set; }
    public string ModelID { get; set; }
    public string SpecialIdentifier { get; set; }
    public string DirectoryName { get; set; }
    public string Icon { get; set; }
    public string Tips { get; set; }
    public string Desc { get; set; }
    public string MetaKeyword { get; set; }
    public string MetaDescription { get; set; }
    public Nullable<bool> IsElite { get; set; }
    public Nullable<int> OpenType { get; set; }
    public string TemplatePath { get; set; }
    public string SearchTemplatePath { get; set; }
    public Nullable<int> PagePostfix { get; set; }
    public Nullable<bool> Ishtml { get; set; }
    public Nullable<int> ListPageSaveType { get; set; }
    public long Orders { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public bool IsDel { get; set; }
    public int SiteID { get; set; }
}

public partial class K_SpecialInfo
{
    public System.Guid ID { get; set; }
    public string SpecialID { get; set; }
    public string SpecialMenuID { get; set; }
    public string InfoID { get; set; }
    public string CommentTitle { get; set; }
    public string OpposeView { get; set; }
    public string SupportView { get; set; }
    public Nullable<int> OpposeCount { get; set; }
    public Nullable<int> SupportCount { get; set; }
}

public partial class K_SpecialMenu
{
    public string ID { get; set; }
    public string ModelID { get; set; }
    public string Name { get; set; }
    public string SpecialID { get; set; }
    public string DirectoryName { get; set; }
    public string Tips { get; set; }
    public string Desc { get; set; }
    public string MetaDescription { get; set; }
    public Nullable<int> PagePostfix { get; set; }
    public string MetaKeyword { get; set; }
    public Nullable<int> OpenType { get; set; }
    public string TemplatePath { get; set; }
    public string RSTemplatePath { get; set; }
    public Nullable<bool> Ishtml { get; set; }
    public Nullable<int> ListPageSaveType { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public long Orders { get; set; }
    public bool IsDel { get; set; }
}

public partial class K_SysAccount
{
    public int UserID { get; set; }
    public string UserName { get; set; }
    public string PassWord { get; set; }
    public Nullable<int> Orders { get; set; }
    public Nullable<bool> IsValid { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public Nullable<bool> IsDel { get; set; }
    public Nullable<System.DateTime> DelTime { get; set; }
    public string Memorandum { get; set; }
    public string NodeCode { get; set; }
}

public partial class K_SysAccountPermit
{
    public int ID { get; set; }
    public Nullable<int> AccountID { get; set; }
    public Nullable<System.Guid> PermitCode { get; set; }
    public Nullable<System.Guid> NodeID { get; set; }
}

public partial class K_SysAccountSite
{
    public int ID { get; set; }
    public Nullable<int> UserID { get; set; }
    public Nullable<int> SiteID { get; set; }
    public Nullable<bool> IsValid { get; set; }
    public Nullable<System.DateTime> LoginDate { get; set; }
    public string IP { get; set; }
    public Nullable<int> LoginCount { get; set; }
    public Nullable<System.DateTime> LastLoginDate { get; set; }
    public string LastLoginIP { get; set; }
    public Nullable<bool> IsDel { get; set; }
    public Nullable<System.DateTime> DelTime { get; set; }
    public string PoSition { get; set; }
}

public partial class K_SysActionPermit
{
    public System.Guid ID { get; set; }
    public Nullable<System.Guid> ModuleID { get; set; }
    public string OperCode { get; set; }
    public string OperName { get; set; }
    public string OperOrder { get; set; }
    public Nullable<bool> IsValid { get; set; }
    public string OperDesc { get; set; }
    public string OperEngDesc { get; set; }
    public Nullable<bool> IsDefaultOper { get; set; }
    public Nullable<bool> IsSystem { get; set; }
}

public partial class K_SysLog
{
    public int ID { get; set; }
    public string NodeCode { get; set; }
    public int SiteID { get; set; }
    public string Content { get; set; }
    public System.DateTime AddDate { get; set; }
    public string UserNo { get; set; }
    public string IP { get; set; }
    public string ScriptName { get; set; }
    public string PostContent { get; set; }
    public int LogType { get; set; }
    public Nullable<byte> IsDel { get; set; }
    public Nullable<System.DateTime> DelTime { get; set; }
}

public partial class K_SysModule
{
    public System.Guid ModuleID { get; set; }
    public string ModuleCode { get; set; }
    public string ModuleName { get; set; }
    public string LinkUrl { get; set; }
    public Nullable<bool> IsValid { get; set; }
    public string ModuleOrder { get; set; }
    public string ModuleDesc { get; set; }
    public string ModuleEncDesc { get; set; }
    public Nullable<bool> IsSystem { get; set; }
    public Nullable<int> ModuleType { get; set; }
    public string TableName { get; set; }
}

public partial class K_SysModuleNode
{
    public System.Guid NodeID { get; set; }
    public string NodeCode { get; set; }
    public string NodeName { get; set; }
    public string NodeType { get; set; }
    public string LinkURL { get; set; }
    public string ParentNode { get; set; }
    public Nullable<System.Guid> ModuleID { get; set; }
    public Nullable<bool> IsLeftDisplay { get; set; }
    public Nullable<bool> IsValid { get; set; }
    public Nullable<int> NodelOrder { get; set; }
    public string NodelDesc { get; set; }
    public string NodelEngDesc { get; set; }
    public string NodelIcon { get; set; }
    public string MouseOverImg { get; set; }
    public string CurrentImg { get; set; }
    public Nullable<bool> IsSystem { get; set; }
    public Nullable<bool> IsWeb { get; set; }
    public Nullable<int> WebSiteID { get; set; }
    public string NodeDir { get; set; }
    public string Tips { get; set; }
    public string Meta_Keywords { get; set; }
    public string Meta_Description { get; set; }
    public string Custom_Content { get; set; }
    public string DefaultTemplate { get; set; }
    public string ListPageTemplate { get; set; }
    public string ContentTemplate { get; set; }
    public Nullable<bool> EnableSubDomain { get; set; }
    public string SubDomain { get; set; }
    public string Settings { get; set; }
    public string Creater { get; set; }
    public Nullable<System.DateTime> CreateDate { get; set; }
    public string ReviewFlowID { get; set; }
    public Nullable<int> OpenType { get; set; }
    public Nullable<int> PurviewType { get; set; }
    public Nullable<bool> IsEnableComment { get; set; }
    public Nullable<bool> IsCreateListPage { get; set; }
    public Nullable<int> IncrementalUpdatePages { get; set; }
    public Nullable<bool> IsEnableIndexCache { get; set; }
    public Nullable<int> ListPageSavePathType { get; set; }
    public string ListPagePostFix { get; set; }
    public Nullable<bool> IsCreateContentPage { get; set; }
    public string ContentPageHtmlRule { get; set; }
    public Nullable<int> AutoCreateHtmlType { get; set; }
    public string Custom_Images { get; set; }
    public Nullable<bool> IsContainWebContent { get; set; }
    public Nullable<int> ColumnType { get; set; }
    public Nullable<bool> IsCreateColumn { get; set; }
    public Nullable<bool> IsDel { get; set; }
    public string CustomManageLink { get; set; }
    public string PageTitle { get; set; }
    public Nullable<System.DateTime> DelTime { get; set; }
    public string Banner { get; set; }
    public Nullable<bool> IsTopMenuShow { get; set; }
    public Nullable<bool> IsLeftMenuShow { get; set; }
}

public partial class K_SysPublicOper
{
    public string OperName { get; set; }
    public string Title { get; set; }
    public Nullable<bool> IsValid { get; set; }
    public string ModuleName { get; set; }
    public Nullable<bool> IsPublic { get; set; }
}

public partial class K_SysRole
{
    public System.Guid RoleCode { get; set; }
    public string RoleName { get; set; }
    public Nullable<int> SiteID { get; set; }
    public Nullable<int> InputID { get; set; }
    public string InputPerson { get; set; }
    public Nullable<System.DateTime> InputDate { get; set; }
    public string RoleDescription { get; set; }
    public Nullable<int> RoleOrder { get; set; }
    public Nullable<bool> IsDel { get; set; }
    public Nullable<System.DateTime> DelTime { get; set; }
}

public partial class K_SysRolePermit
{
    public int ID { get; set; }
    public Nullable<System.Guid> RoleCode { get; set; }
    public Nullable<System.Guid> PermitCode { get; set; }
    public Nullable<System.Guid> NodeID { get; set; }
}

public partial class K_SysUserGroup
{
    public int ID { get; set; }
    public System.Guid UserGroupCode { get; set; }
    public string UserGroupName { get; set; }
    public Nullable<int> SiteID { get; set; }
    public Nullable<bool> IsParent { get; set; }
    public string NumCode { get; set; }
    public string ParentNumCode { get; set; }
    public Nullable<int> InputID { get; set; }
    public string InputPerson { get; set; }
    public Nullable<System.DateTime> InputDate { get; set; }
    public string UserGroupRemark { get; set; }
    public Nullable<int> UserGroupOrder { get; set; }
    public Nullable<bool> IsDel { get; set; }
    public Nullable<System.DateTime> DelTime { get; set; }
}

public partial class K_SysUserGroupPermit
{
    public int ID { get; set; }
    public Nullable<System.Guid> UserGroupCode { get; set; }
    public Nullable<System.Guid> PermitCode { get; set; }
    public Nullable<System.Guid> NodeID { get; set; }
}

public partial class K_SysUserGroupRole
{
    public int ID { get; set; }
    public Nullable<System.Guid> UserGroupCode { get; set; }
    public Nullable<System.Guid> RoleCode { get; set; }
}

public partial class K_SysUserRole
{
    public int ID { get; set; }
    public Nullable<int> UserID { get; set; }
    public Nullable<System.Guid> UserGroupCode { get; set; }
}

public partial class K_SysWebSite
{
    public int SiteID { get; set; }
    public string SiteName { get; set; }
    public string Directory { get; set; }
    public string SiteUrl { get; set; }
    public Nullable<bool> IsMainSite { get; set; }
    public string SettingsXML { get; set; }
}

public partial class K_TemplateProject
{
    public System.Guid ID { get; set; }
    public string Title { get; set; }
    public string Directory { get; set; }
    public string Devise { get; set; }
    public int Width { get; set; }
    public string Intro { get; set; }
    public bool IsDefault { get; set; }
    public string Thumbnail { get; set; }
    public bool IsDel { get; set; }
    public System.DateTime DeTime { get; set; }
    public string NodeCode { get; set; }
    public int SiteID { get; set; }
    public string AddMan { get; set; }
    public System.DateTime AddTime { get; set; }
}

public partial class K_Types
{
    public string TypeId { get; set; }
    public string TypeName { get; set; }
    public string TypeParent { get; set; }
    public Nullable<int> Orders { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public string MenuID { get; set; }
    public Nullable<int> IsPub { get; set; }
    public string Digest { get; set; }
    public string MenuString { get; set; }
    public Nullable<int> TypeExpandInt { get; set; }
    public string TypeExpandChar1 { get; set; }
    public string TypeExpandChar2 { get; set; }
    public string TypeExpandChar3 { get; set; }
}

public partial class K_U_Common
{
    public string ID { get; set; }
    public Nullable<int> IsDel { get; set; }
    public Nullable<int> IsEnable { get; set; }
    public Nullable<int> IsArchiving { get; set; }
    public Nullable<long> Orders { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public Nullable<System.DateTime> DelTime { get; set; }
    public int SiteID { get; set; }
    public string NodeCode { get; set; }
    public Nullable<int> FlowState { get; set; }
    public string ReferenceID { get; set; }
    public string AddMan { get; set; }
    public string Title { get; set; }
    public string UserName { get; set; }
    public Nullable<System.DateTime> PubDate { get; set; }
    public string Intro { get; set; }
    public string BigImg { get; set; }
    public string Attach { get; set; }
    public string SmallImg { get; set; }
    public string listimage { get; set; }
    public string Password { get; set; }
    public string PhotoAlbum { get; set; }
    public string AttachList { get; set; }
    public string Interest { get; set; }
    public string detail { get; set; }
    public string Sex { get; set; }
}

public partial class K_U_Contact
{
    public string ID { get; set; }
    public Nullable<int> IsDel { get; set; }
    public Nullable<int> IsEnable { get; set; }
    public Nullable<int> IsArchiving { get; set; }
    public Nullable<long> Orders { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public Nullable<System.DateTime> DelTime { get; set; }
    public int SiteID { get; set; }
    public string NodeCode { get; set; }
    public Nullable<int> FlowState { get; set; }
    public string ReferenceID { get; set; }
    public string AddMan { get; set; }
    public string Title { get; set; }
}

public partial class K_U_DownLoad
{
    public string ID { get; set; }
    public Nullable<int> IsDel { get; set; }
    public Nullable<int> IsEnable { get; set; }
    public Nullable<int> IsArchiving { get; set; }
    public Nullable<long> Orders { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public Nullable<System.DateTime> DelTime { get; set; }
    public int SiteID { get; set; }
    public string NodeCode { get; set; }
    public Nullable<int> FlowState { get; set; }
    public string ReferenceID { get; set; }
    public string AddMan { get; set; }
    public string Title { get; set; }
    public string Files { get; set; }
    public Nullable<System.DateTime> PubDate { get; set; }
}

public partial class K_U_friendlink
{
    public string ID { get; set; }
    public Nullable<int> IsDel { get; set; }
    public Nullable<int> IsEnable { get; set; }
    public Nullable<int> IsArchiving { get; set; }
    public Nullable<long> Orders { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public Nullable<System.DateTime> DelTime { get; set; }
    public int SiteID { get; set; }
    public string NodeCode { get; set; }
    public Nullable<int> FlowState { get; set; }
    public string ReferenceID { get; set; }
    public string AddMan { get; set; }
    public string Title { get; set; }
    public string Links { get; set; }
    public string BigImg { get; set; }
    public string MetaKeyword { get; set; }
    public string Metadescript { get; set; }
    public string PageTitle { get; set; }
    public int IsHtml { get; set; }
}

public partial class K_U_Jobs
{
    public string ID { get; set; }
    public Nullable<int> IsDel { get; set; }
    public Nullable<int> IsEnable { get; set; }
    public Nullable<int> IsArchiving { get; set; }
    public Nullable<long> Orders { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public Nullable<System.DateTime> DelTime { get; set; }
    public int SiteID { get; set; }
    public string NodeCode { get; set; }
    public Nullable<int> FlowState { get; set; }
    public string ReferenceID { get; set; }
    public string AddMan { get; set; }
    public string Title { get; set; }
    public string WorkAddr { get; set; }
    public string Num { get; set; }
    public string Salary { get; set; }
    public Nullable<System.DateTime> PubDate { get; set; }
    public string Requirement { get; set; }
    public string Content { get; set; }
}

public partial class K_U_Member
{
    public string ID { get; set; }
    public Nullable<int> IsDel { get; set; }
    public Nullable<int> IsEnable { get; set; }
    public Nullable<int> IsArchiving { get; set; }
    public Nullable<long> Orders { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public Nullable<System.DateTime> DelTime { get; set; }
    public int SiteID { get; set; }
    public string NodeCode { get; set; }
    public Nullable<int> FlowState { get; set; }
    public string ReferenceID { get; set; }
    public string AddMan { get; set; }
    public string Title { get; set; }
    public string Mobile { get; set; }
    public string Email { get; set; }
    public string Password { get; set; }
    public string ContactPerson { get; set; }
    public string Company { get; set; }
    public string Province { get; set; }
    public string City { get; set; }
    public string Area { get; set; }
    public string Address { get; set; }
    public string QQ { get; set; }
    public string Type { get; set; }
    public Nullable<System.DateTime> RegTime { get; set; }
    public Nullable<System.DateTime> LastLoginTime { get; set; }
}

public partial class K_U_News
{
    public string ID { get; set; }
    public Nullable<int> IsDel { get; set; }
    public Nullable<int> IsEnable { get; set; }
    public Nullable<int> IsArchiving { get; set; }
    public Nullable<long> Orders { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public Nullable<System.DateTime> DelTime { get; set; }
    public int SiteID { get; set; }
    public string NodeCode { get; set; }
    public Nullable<int> FlowState { get; set; }
    public string ReferenceID { get; set; }
    public string AddMan { get; set; }
    public string MetaDescript { get; set; }
    public string MetaKeyword { get; set; }
    public string Title { get; set; }
    public string TitleImg { get; set; }
    public Nullable<System.DateTime> PubDate { get; set; }
    public string Intro { get; set; }
    public string Content { get; set; }
    public string Attach { get; set; }
    public string PageTitle { get; set; }
    public int IsHtml { get; set; }
}

public partial class K_U_PersonIntro
{
    public string ID { get; set; }
    public Nullable<int> IsDel { get; set; }
    public Nullable<int> IsEnable { get; set; }
    public Nullable<int> IsArchiving { get; set; }
    public Nullable<long> Orders { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public Nullable<System.DateTime> DelTime { get; set; }
    public int SiteID { get; set; }
    public string NodeCode { get; set; }
    public Nullable<int> FlowState { get; set; }
    public string ReferenceID { get; set; }
    public string AddMan { get; set; }
    public string Title { get; set; }
    public string TitleImg { get; set; }
    public string Imgs { get; set; }
    public string Html { get; set; }
}

public partial class K_U_product
{
    public string ID { get; set; }
    public Nullable<int> IsDel { get; set; }
    public Nullable<int> IsEnable { get; set; }
    public Nullable<int> IsArchiving { get; set; }
    public Nullable<long> Orders { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public Nullable<System.DateTime> DelTime { get; set; }
    public int SiteID { get; set; }
    public string NodeCode { get; set; }
    public Nullable<int> FlowState { get; set; }
    public string ReferenceID { get; set; }
    public string AddMan { get; set; }
    public string MetaDescript { get; set; }
    public string MetaKeyword { get; set; }
    public string Title { get; set; }
    public Nullable<System.DateTime> PubDate { get; set; }
    public string Intro { get; set; }
    public string BigImg { get; set; }
    public string Content { get; set; }
    public string SmallImg { get; set; }
    public string Attach { get; set; }
    public string tuij { get; set; }
    public string productuse { get; set; }
    public string PageTitle { get; set; }
    public int IsHtml { get; set; }
    public string xc { get; set; }
    public string dtcs { get; set; }
    public string jjfa { get; set; }
    public string cpal { get; set; }
}

public partial class K_U_ProductType
{
    public string ID { get; set; }
    public Nullable<int> IsDel { get; set; }
    public Nullable<int> IsEnable { get; set; }
    public Nullable<int> IsArchiving { get; set; }
    public Nullable<long> Orders { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public Nullable<System.DateTime> DelTime { get; set; }
    public int SiteID { get; set; }
    public string NodeCode { get; set; }
    public Nullable<int> FlowState { get; set; }
    public string ReferenceID { get; set; }
    public string AddMan { get; set; }
    public string Title { get; set; }
}

public partial class K_U_Show
{
    public string ID { get; set; }
    public Nullable<int> IsDel { get; set; }
    public Nullable<int> IsEnable { get; set; }
    public Nullable<int> IsArchiving { get; set; }
    public Nullable<long> Orders { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public Nullable<System.DateTime> DelTime { get; set; }
    public int SiteID { get; set; }
    public string NodeCode { get; set; }
    public Nullable<int> FlowState { get; set; }
    public string ReferenceID { get; set; }
    public string AddMan { get; set; }
    public string Title { get; set; }
    public string ShowDate { get; set; }
    public string Addr { get; set; }
    public string Team { get; set; }
}

public partial class K_U_Thanks
{
    public string ID { get; set; }
    public Nullable<int> IsDel { get; set; }
    public Nullable<int> IsEnable { get; set; }
    public Nullable<int> IsArchiving { get; set; }
    public Nullable<long> Orders { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public Nullable<System.DateTime> DelTime { get; set; }
    public int SiteID { get; set; }
    public string NodeCode { get; set; }
    public Nullable<int> FlowState { get; set; }
    public string ReferenceID { get; set; }
    public string AddMan { get; set; }
    public string Title { get; set; }
    public string TitleImg { get; set; }
    public string HtmlContent { get; set; }
}

public partial class K_WebSiteTemplate
{
    public int TemplateID { get; set; }
    public string TemplateName { get; set; }
}

public partial class K_WebSiteTemplateNode
{
    public int ID { get; set; }
    public Nullable<int> TemplateID { get; set; }
    public string NodeCode { get; set; }
    public string NodeName { get; set; }
    public string NodeType { get; set; }
    public string LinkURL { get; set; }
    public string ParentNode { get; set; }
    public Nullable<bool> IsValid { get; set; }
    public Nullable<System.Guid> ModuleID { get; set; }
    public string NodelOrder { get; set; }
    public string NodelDesc { get; set; }
    public string NodelEngDesc { get; set; }
    public Nullable<bool> IsSystem { get; set; }
    public Nullable<bool> IsWeb { get; set; }
    public string ReviewFlowID { get; set; }
    public Nullable<bool> IsContainWebContent { get; set; }
    public Nullable<bool> IsLeftDisplay { get; set; }
}

public partial class K_WebSiteTemplatePermit
{
    public int ID { get; set; }
    public Nullable<int> TemplateID { get; set; }
    public Nullable<System.Guid> PermitCode { get; set; }
    public Nullable<int> TemplateNodeID { get; set; }
}
