//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class K_F_FeedBack
{
    public string ID { get; set; }
    public Nullable<int> IsDel { get; set; }
    public Nullable<int> IsEnable { get; set; }
    public Nullable<int> IsArchiving { get; set; }
    public Nullable<long> Orders { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public Nullable<System.DateTime> DelTime { get; set; }
    public int SiteID { get; set; }
    public string NodeCode { get; set; }
    public Nullable<int> FlowState { get; set; }
    public string ReferenceID { get; set; }
    public string AddMan { get; set; }
    public string IP { get; set; }
    public string Title { get; set; }
    public string Name { get; set; }
    public string EMail { get; set; }
    public string LinkPhone { get; set; }
    public string LinkAddress { get; set; }
    public string Content { get; set; }
    public string DealResult { get; set; }
}

public partial class K_FlowStep
{
    public string ID { get; set; }
    public Nullable<int> Orders { get; set; }
    public Nullable<bool> IsDel { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public string AddMan { get; set; }
    public string Name { get; set; }
    public string Desc { get; set; }
    public string SuccessName { get; set; }
    public Nullable<int> SuccessState { get; set; }
    public string FailName { get; set; }
    public Nullable<int> FailState { get; set; }
    public string GroupID { get; set; }
    public string ReviewFlowStateGroup { get; set; }
    public string ReviewFlowId { get; set; }
    public Nullable<bool> IsEnable { get; set; }
    public string NodeCode { get; set; }
    public Nullable<System.DateTime> delTime { get; set; }
}

public partial class K_Member
{
    public System.Guid MemberID { get; set; }
    public string UserName { get; set; }
    public string Password { get; set; }
    public string GroupID { get; set; }
    public string ModleID { get; set; }
    public string Email { get; set; }
    public Nullable<double> Funds { get; set; }
    public Nullable<double> FundFreeze { get; set; }
    public int Point { get; set; }
    public int Integral { get; set; }
    public Nullable<byte> StateID { get; set; }
    public Nullable<byte> IsCheck { get; set; }
    public bool IsEmailValid { get; set; }
    public Nullable<bool> IsDel { get; set; }
    public string RegitIP { get; set; }
    public System.DateTime RegitDate { get; set; }
    public string PreLoginIP { get; set; }
    public Nullable<System.DateTime> PreLoginDate { get; set; }
    public string LastLoginIP { get; set; }
    public Nullable<System.DateTime> LastLoginDate { get; set; }
    public Nullable<System.DateTime> LastPub { get; set; }
    public int LoginTimes { get; set; }
    public string NodeCode { get; set; }
    public Nullable<int> SiteID { get; set; }
    public string HeadImg { get; set; }
    public string ThemeID { get; set; }
    public string UserGroup { get; set; }
    public string PubTipLevel { get; set; }
    public int ReadRight { get; set; }
    public int Golds { get; set; }
    public int Prestige { get; set; }
    public int SaveGolds { get; set; }
    public int Tips { get; set; }
    public int VeryTips { get; set; }
    public int TotalOnlineHour { get; set; }
    public int MonthHour { get; set; }
    public string Moderator { get; set; }
    public int BestAnswerCount { get; set; }
    public string Gender { get; set; }
    public string Token { get; set; }
    public string PwdVe { get; set; }
    public string RealName { get; set; }
    public Nullable<System.DateTime> Birthday { get; set; }
    public string Mobile { get; set; }
    public Nullable<byte> Marriage { get; set; }
    public string Intro { get; set; }
}

public partial class K_MemberGroup
{
    public string ID { get; set; }
    public string GroupName { get; set; }
    public string ServerIntro { get; set; }
    public Nullable<byte> IsVisit { get; set; }
    public Nullable<byte> IsSearch { get; set; }
    public Nullable<byte> IsPub { get; set; }
    public Nullable<byte> IsSelfUpgrade { get; set; }
    public Nullable<double> YearPrices { get; set; }
    public Nullable<double> MonthPrices { get; set; }
    public Nullable<double> DayPrices { get; set; }
    public Nullable<byte> IsDisable { get; set; }
    public Nullable<int> Orders { get; set; }
    public Nullable<bool> IsDel { get; set; }
    public string AddMan { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public string NodeCode { get; set; }
    public Nullable<int> SiteID { get; set; }
    public Nullable<int> Toplimit { get; set; }
    public Nullable<int> Lowerlimit { get; set; }
    public Nullable<int> Discount { get; set; }
    public Nullable<bool> IsShowPrice { get; set; }
}

public partial class K_Special
{
    public string ID { get; set; }
    public string Name { get; set; }
    public string ModelID { get; set; }
    public string SpecialIdentifier { get; set; }
    public string DirectoryName { get; set; }
    public string Icon { get; set; }
    public string Tips { get; set; }
    public string Desc { get; set; }
    public string MetaKeyword { get; set; }
    public string MetaDescription { get; set; }
    public Nullable<bool> IsElite { get; set; }
    public Nullable<int> OpenType { get; set; }
    public string TemplatePath { get; set; }
    public string SearchTemplatePath { get; set; }
    public Nullable<int> PagePostfix { get; set; }
    public Nullable<bool> Ishtml { get; set; }
    public Nullable<int> ListPageSaveType { get; set; }
    public long Orders { get; set; }
    public Nullable<System.DateTime> AddDate { get; set; }
    public bool IsDel { get; set; }
    public int SiteID { get; set; }
}

public partial class K_SpecialInfo
{
    public System.Guid ID { get; set; }
    public string SpecialID { get; set; }
    public string SpecialMenuID { get; set; }
    public string InfoID { get; set; }
    public string CommentTitle { get; set; }
    public string OpposeView { get; set; }
    public string SupportView { get; set; }
    public Nullable<int> OpposeCount { get; set; }
    public Nullable<int> SupportCount { get; set; }
}
